### PR TITLE
Replace remount func

### PR DESCRIPTION
**Pull request by Lakr233**
Replace remount function. Support up to 11.3.1.
It seems to work with multi path and app group but my device can NOT use vfs or I'm not lucky enough. Fork you.
 Untested with vfs.

//add Do it action to alert.

APFS remount func by Pwn20wnd

### CODE REVIEW

**Comment by midnightchip** [comment]
I tried adapting for the multi_path version, and it does indeed remount as r/w assuming the log isn't lying, however Osiris crashes right after it has Mounted as R/W

**Comment by Lakr233** [comment]
@midnightchip did you succeed with vfs bug?

**Comment by midnightchip** [comment]
@Co2333 I havn't had any success with vfs in general, I will try now.

**Comment by midnightchip** [comment]
Ok, I got it to run, and it crashes after mounting RW as well `Mounted / as read write :-)
Using cached me @0xffffffe005964100
Before - My UID: 0 (kernel: 0), My GID: 501 (kernel: 0)
current CS Flags: 0x0
AFTER: 0x20004005
After - My UID: 0 (kernel: 0), My GID: 501 (kernel: 0)`

**Comment by midnightchip** [comment]
also I did see this `got amfi!
fs_snapshot_list: Invalid argument`

**Comment by midnightchip** [comment]
@Co2333 I know why its not working, its missing the actual remount bit, this is just the persistence patch. We need a version of this: https://ghostbin.com/paste/e2re5.

**Comment by Lakr233** [comment]
🍏I will try it again and still use multi path.

**Comment by yo-bur** [comment]
It crashes on line `1218` in `sploit.c` with the method from `Qilin`: `moveFileFromAppDir`. (iPhone 6 11.3.1)

**Comment by Lakr233** [comment]
There appears a problem. 
I don't really know, but it seems not, if we can directly run script to mount it via root permission.
So I'm trying to move some func out/replace QiLin tool as it is not open source anymore.
This time I tried some function in async_weak to try to get kennel permission but it is too hard for me to do the stuff. I got KenrelCredAddr out of QiLin and send to kwrite but it always cause problem.

`#include <sys/mount.h>`
`int rv = mount("apfs", "/var/mount/", 0, "/dev/disk0s1s1");`

This will complete all mount stuff and then we use remount function to make change stable across reboot.

But mount always failed. So I tried to use following codes:
`kwrite64(our_addr, kernel_cred_addr);`
I don't know how to use kread as @midnightchip mention. /See that url code.

All in all, remount work, mount not. Fork that.

Ps: If we can get QiLin Tool's source code, it would be fix soon.
We just need to add change mount position to /var/mount or some where we can and mount it for now. Then we can write anything we want to desk and change will always appear to /.




The following codes is all about kwreit and kread:

`
kern_return_t mach_vm_write(
                            vm_map_t target_task,
                            mach_vm_address_t address,
                            vm_offset_t data,
                            mach_msg_type_number_t dataCnt);

size_t kwrite(uint64_t where, const void *p, size_t size) {
    int rv;
    size_t offset = 0;
    while (offset < size) {
        size_t chunk = 2048;
        if (chunk > size - offset) {
            chunk = size - offset;
        }
        rv = mach_vm_write(tfpo_check(), where + offset, (mach_vm_offset_t)p + offset, chunk);
        if (rv) {
            printf("[fun_utils] error on kwrite(0x%016llx)\n", (offset + where));
            break;
        }
        offset += chunk;
    }
    return offset;
}

void kwrite32(uint64_t where, uint32_t what) {
    uint32_t _what = what;
    kwrite(where, &_what, sizeof(uint32_t));
}


void kwrite64(uint64_t where, uint64_t what) {
    uint64_t _what = what;
    kwrite(where, &_what, sizeof(uint64_t));
}

kern_return_t mach_vm_read_overwrite(
                                     vm_map_t target_task,
                                     mach_vm_address_t address,
                                     mach_vm_size_t size,
                                     mach_vm_address_t data,
                                     mach_vm_size_t *outsize);

size_t kread(uint64_t where, void *p, size_t size) {
    int rv;
    size_t offset = 0;
    while (offset < size) {
        mach_vm_size_t sz, chunk = 2048;
        if (chunk > size - offset) {
            chunk = size - offset;
        }
        rv = mach_vm_read_overwrite(tfpo_check(), where + offset, chunk, (mach_vm_address_t)p + offset, &sz);
        if (rv || sz == 0) {
            printf("[fun_utils] error on kread(0x%016llx)\n", (offset + where));
            break;
        }
        offset += sz;
    }
    return offset;
}

uint32_t kread32(uint64_t where) {
    uint32_t out;
    kread(where, &out, sizeof(uint32_t));
    return out;
}

uint64_t kread64(uint64_t where) {
    uint64_t out;
    kread(where, &out, sizeof(uint64_t));
    return out;
}`

**Pull request closed without merging**
